# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhepEvZwdm5yUd5DffNY4CBtu4Sohl2t
"""

import pandas as pd
titanic_data={
    "passengerid":[1,2,3,4,5,6],
    "name":["a","b","c","d","e","f"],
    "age":[22,33,44,55,23,4],
    "sex":["male","female","male","male","female","female"],
    "pclass":[3,2,2,3,1,3,],
    "survived":[0,1,1,1,0,0],
    "fare":[100,200,300,400,500,600],
    "embarked":["s","c","s","s","c","q"]
}
df=pd.DataFrame(titanic_data)
print(df)

#Label Encoding(mappimg categories to numbers)explanation:labrl encoding  coverts tcategorical value  into numeric  codes

import pandas as pd
print(df["sex"].unique())

df["sex"]=df["sex"].map({"male":0,"female":1})
print(df)
df["sex"].head()

df1=pd.get_dummies(df, columns=["embarked"],drop_first=True,dtype=int)
print(df1.head())

df1=pd.get_dummies(df, columns=["embarked"],drop_first=False,dtype=int)
print(df1.head())

#normalization is used to rescale numeric data xso that values li in the range often 0 to 1

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
d=pd.DataFrame({'profit':[22,500,1000,1500,3000]})
scaler=MinMaxScaler()
d["Profit_Normalized"]=scaler.fit_transform(d[["profit"]])
print(d)

import numpy as np
d=pd.DataFrame({'sales':[10,50,200,1000,5000]})
d["sales_log"]=np.log(d["sales"])
print(d)

